sudo: true
language: python

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"

notifications:
  slack: colour-science:Y6lPPcN7y53Js94geqUpqsAP

addons:
  apt:
   sources:
      - ubuntu-toolchain-r-test
   packages:
      - libboost-all-dev
      - libopenexr-dev
      - libilmbase-dev
      - libimage-exiftool-perl

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - PACKAGES="python=${PYTHON_VERSION}"
  - PACKAGES="${PACKAGES} scipy"; if [ ${SCIPY_VERSION} ]; then PACKAGES="${PACKAGES}=${SCIPY_VERSION}"; fi
  - PACKAGES="${PACKAGES} matplotlib"; if [ ${MATPLOTLIB_VERSION} ]; then PACKAGES="${PACKAGES}=${MATPLOTLIB_VERSION}"; fi
  # TODO: Investigate reason why *dcraw* cannot be installed along other packages.
  - sudo apt-get install dcraw
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.5.21.tar.gz -O /tmp/OpenImageIO-1.5.21.tar.gz
  - tar -xvf /tmp/OpenImageIO-1.5.21.tar.gz
  - cd oiio-Release-1.5.21
  - make
  - cd /home/travis/build/colour-science/colour-hdri

install:
  - conda create --yes --quiet -n colour-hdri-test ${PACKAGES} pip setuptools nose
  - source activate colour-hdri-test
  - pip install colour-science six recordclass coverage coveralls flake8 mock==1.0.1
  - sudo cp /home/travis/build/colour-science/colour-hdri/oiio-Release-1.5.21/dist/linux64/bin/* /usr/local/bin/
  - sudo cp /home/travis/build/colour-science/colour-hdri/oiio-Release-1.5.21/dist/linux64/lib/* /usr/local/lib/
  - cp /home/travis/build/colour-science/colour-hdri/oiio-Release-1.5.21/dist/linux64/python/OpenImageIO.so /home/travis/miniconda/envs/colour-hdri-test/lib/python2.7/site-packages/

script:
  - flake8 colour_hdri
  - nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS,+NORMALIZE_WHITESPACE --with-coverage --cover-package=colour_hdri -exclude-dir=

after_success:
  - coveralls
