name: Continuous Integration

on: [push, pull_request]

jobs:
  continuous-integration:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-18.04, windows-latest]
        python-version: [3.6, 3.7, 3.8]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Environment Variables
      run: |
        echo "CI_PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
        echo "CI_PACKAGE=colour_hdri" >> $GITHUB_ENV
        echo "CI_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_REPO_TOKEN }}" >> $GITHUB_ENV
        echo "MPLBACKEND=AGG" >> $GITHUB_ENV
      shell: bash
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies (macOS)
      if: matrix.os == 'macOS-latest'
      run: |
        brew install dcraw exiftool gnu-sed
        brew cask install adobe-dng-converter
        ln -s /usr/local/bin/gsed /usr/local/bin/sed
      shell: bash
    - name: Install Dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-18.04'
      run: |
        sudo apt-get update
        sudo apt-get --yes install dcraw libimage-exiftool-perl
      shell: bash
    - name: Install Dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -L https://exiftool.org/exiftool-12.11.zip -o exiftool-12.11.zip
        unzip -d exiftool exiftool-12.11.zip
        cp exiftool/exiftool\(-k\).exe exiftool/exiftool.exe
        echo "$PWD/exiftool" >> $GITHUB_PATH
        curl -L https://cdn.fastpictureviewer.com/bin/dcraw.zip?v=201605100 -o dcraw.zip
        unzip -d dcraw dcraw.zip
        echo "$PWD/dcraw" >> $GITHUB_PATH
      shell: bash
    - name: Install Adobe DNG Converter (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -L https://download.adobe.com/pub/adobe/dng/win/DNGConverter_11_4.exe -o DNGConverter_11_4.exe
        DNGConverter_11_4.exe /S
        echo "C:\Program Files\Adobe\Adobe DNG Converter" >> $GITHUB_PATH
      shell: cmd
    - name: Add Adobe DNG Converter to %PATH% (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "C:\Program Files\Adobe\Adobe DNG Converter" >> $GITHUB_PATH
      shell: bash
    - name: Install Poetry
      run: |
        curl -L https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py -o get-poetry.py
        python get-poetry.py --version 1.0.10
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      shell: bash
    - name: Install Package Dependencies
      run: |
        poetry run python -m pip install --upgrade pip
        poetry install --extras "plotting"
        poetry run python -c "import imageio;imageio.plugins.freeimage.download()"
      shell: bash
    - name: Lint with flake8
      run: |
        poetry run flake8 $CI_PACKAGE --count --show-source --statistics
      shell: bash
    - name: Test with nosetests
      run: |
        poetry run python -W ignore -m nose -q -v --with-doctest --doctest-options=+ELLIPSIS --with-coverage --traverse-namespace --cover-package=$CI_PACKAGE $CI_PACKAGE
      shell: bash
    - name: Upload Coverage to coveralls.io
      run: |
        if [ -z "$COVERALLS_REPO_TOKEN" ]; then echo \"COVERALLS_REPO_TOKEN\" secret is undefined!; else poetry run coveralls; fi
      shell: bash
